"""Mock realistic mutual fund data for the MF Intelligence app."""
from datetime import datetime, timezone, timedelta

# Six representative Indian mutual funds across categories
FUNDS = [
    {
        "id": "axis-bluechip",
        "name": "Axis Bluechip Fund - Direct Plan - Growth",
        "amc": "Axis Mutual Fund",
        "category": "Large Cap",
        "previous_category": "Large Cap",
        "benchmark": "NIFTY 100 TRI",
        "manager": "Shreyash Devalkar",
        "previous_manager": "Shreyash Devalkar",
        "objective": "To achieve long-term capital appreciation by investing in a diversified portfolio of large cap equity and equity related instruments.",
        "previous_objective": "To achieve long-term capital appreciation by investing in a diversified portfolio of large cap equity and equity related instruments.",
        "previous_name": "Axis Bluechip Fund - Direct Plan - Growth",
        "nav": 58.42,
        "aum_cr": 33450,
        "expense_ratio": 0.59,
        "inception": "2010-01-05",
    },
    {
        "id": "parag-flexi",
        "name": "Parag Parikh Flexi Cap Fund - Direct - Growth",
        "amc": "PPFAS Mutual Fund",
        "category": "Flexi Cap",
        "previous_category": "Multi Cap",
        "benchmark": "NIFTY 500 TRI",
        "manager": "Rajeev Thakkar, Raunak Onkar",
        "previous_manager": "Rajeev Thakkar",
        "objective": "Long term capital appreciation through a diversified portfolio of equity & equity related instruments across market caps and geographies.",
        "previous_objective": "Long term capital appreciation through a diversified portfolio of equity & equity related instruments across market caps and geographies.",
        "previous_name": "Parag Parikh Flexi Cap Fund - Direct - Growth",
        "nav": 81.13,
        "aum_cr": 78230,
        "expense_ratio": 0.61,
        "inception": "2013-05-24",
    },
    {
        "id": "mirae-largemid",
        "name": "Mirae Asset Large & Midcap Fund - Direct - Growth",
        "amc": "Mirae Asset Mutual Fund",
        "category": "Large & Mid Cap",
        "previous_category": "Large & Mid Cap",
        "benchmark": "NIFTY Large Midcap 250 TRI",
        "manager": "Neelesh Surana, Ankit Jain",
        "previous_manager": "Neelesh Surana, Ankit Jain",
        "objective": "Capital appreciation through investments in a diversified portfolio of large and mid cap stocks.",
        "previous_objective": "Capital appreciation through investments in a diversified portfolio of large and mid cap stocks.",
        "previous_name": "Mirae Asset Emerging Bluechip Fund - Direct - Growth",
        "nav": 132.67,
        "aum_cr": 38900,
        "expense_ratio": 0.59,
        "inception": "2010-07-09",
    },
    {
        "id": "kotak-emerg",
        "name": "Kotak Emerging Equity Fund - Direct - Growth",
        "amc": "Kotak Mahindra Mutual Fund",
        "category": "Mid Cap",
        "previous_category": "Mid Cap",
        "benchmark": "NIFTY Midcap 150 TRI",
        "manager": "Pankaj Tibrewal",
        "previous_manager": "Pankaj Tibrewal",
        "objective": "Long term capital appreciation by investing predominantly in mid cap companies.",
        "previous_objective": "Long term capital appreciation by investing predominantly in mid cap companies.",
        "previous_name": "Kotak Emerging Equity Fund - Direct - Growth",
        "nav": 113.21,
        "aum_cr": 41200,
        "expense_ratio": 0.51,
        "inception": "2007-03-30",
    },
    {
        "id": "sbi-smallcap",
        "name": "SBI Small Cap Fund - Direct Plan - Growth",
        "amc": "SBI Mutual Fund",
        "category": "Small Cap",
        "previous_category": "Small Cap",
        "benchmark": "S&P BSE 250 SmallCap TRI",
        "manager": "R. Srinivasan",
        "previous_manager": "R. Srinivasan",
        "objective": "Long term capital appreciation by investing predominantly in equity of small cap companies.",
        "previous_objective": "Long term capital appreciation by investing in equity of small cap companies and equity-related instruments.",
        "previous_name": "SBI Small Cap Fund - Direct Plan - Growth",
        "nav": 162.85,
        "aum_cr": 28950,
        "expense_ratio": 0.65,
        "inception": "2009-09-09",
    },
    {
        "id": "hdfc-balanced",
        "name": "HDFC Balanced Advantage Fund - Direct - Growth",
        "amc": "HDFC Mutual Fund",
        "category": "Dynamic Asset Allocation",
        "previous_category": "Dynamic Asset Allocation",
        "benchmark": "NIFTY 50 Hybrid Composite Debt 50:50",
        "manager": "Anil Bamboli, Gopal Agrawal, Srinivasan Ramamurthy",
        "previous_manager": "Anil Bamboli, Gopal Agrawal",
        "objective": "Capital appreciation/income from a dynamic mix of equity and debt instruments.",
        "previous_objective": "Capital appreciation/income from a dynamic mix of equity and debt instruments.",
        "previous_name": "HDFC Balanced Advantage Fund - Direct - Growth",
        "nav": 412.55,
        "aum_cr": 92340,
        "expense_ratio": 0.74,
        "inception": "2013-01-01",
    },
]

# Holdings: list of {stock, sector, weight}, current and previous month
HOLDINGS = {
    "axis-bluechip": {
        "current": [
            {"stock": "ICICI Bank", "sector": "Financial Services", "weight": 9.2},
            {"stock": "HDFC Bank", "sector": "Financial Services", "weight": 8.7},
            {"stock": "Reliance Industries", "sector": "Energy", "weight": 7.4},
            {"stock": "Infosys", "sector": "IT", "weight": 6.1},
            {"stock": "Bajaj Finance", "sector": "Financial Services", "weight": 5.3},
            {"stock": "TCS", "sector": "IT", "weight": 4.8},
            {"stock": "Avenue Supermarts", "sector": "Consumer", "weight": 4.2},
            {"stock": "Larsen & Toubro", "sector": "Capital Goods", "weight": 3.9},
            {"stock": "Titan Company", "sector": "Consumer", "weight": 3.4},
            {"stock": "Asian Paints", "sector": "Consumer", "weight": 2.1},
        ],
        "previous": [
            {"stock": "ICICI Bank", "sector": "Financial Services", "weight": 8.4},
            {"stock": "HDFC Bank", "sector": "Financial Services", "weight": 9.1},
            {"stock": "Reliance Industries", "sector": "Energy", "weight": 7.0},
            {"stock": "Infosys", "sector": "IT", "weight": 6.5},
            {"stock": "Bajaj Finance", "sector": "Financial Services", "weight": 4.7},
            {"stock": "TCS", "sector": "IT", "weight": 5.2},
            {"stock": "Nestle India", "sector": "Consumer", "weight": 3.8},
            {"stock": "Larsen & Toubro", "sector": "Capital Goods", "weight": 3.2},
            {"stock": "Titan Company", "sector": "Consumer", "weight": 3.5},
            {"stock": "Pidilite Industries", "sector": "Materials", "weight": 2.6},
        ],
    },
    "parag-flexi": {
        "current": [
            {"stock": "HDFC Bank", "sector": "Financial Services", "weight": 8.4},
            {"stock": "Bajaj Holdings", "sector": "Financial Services", "weight": 7.9},
            {"stock": "ITC", "sector": "Consumer", "weight": 7.1},
            {"stock": "Power Grid Corp", "sector": "Utilities", "weight": 6.4},
            {"stock": "Microsoft", "sector": "IT", "weight": 5.9},
            {"stock": "Alphabet", "sector": "IT", "weight": 5.6},
            {"stock": "Coal India", "sector": "Energy", "weight": 4.2},
            {"stock": "ICICI Bank", "sector": "Financial Services", "weight": 4.0},
            {"stock": "Maruti Suzuki", "sector": "Auto", "weight": 3.8},
            {"stock": "Meta Platforms", "sector": "IT", "weight": 3.1},
        ],
        "previous": [
            {"stock": "HDFC Bank", "sector": "Financial Services", "weight": 8.7},
            {"stock": "Bajaj Holdings", "sector": "Financial Services", "weight": 7.5},
            {"stock": "ITC", "sector": "Consumer", "weight": 7.4},
            {"stock": "Power Grid Corp", "sector": "Utilities", "weight": 5.8},
            {"stock": "Microsoft", "sector": "IT", "weight": 6.2},
            {"stock": "Alphabet", "sector": "IT", "weight": 5.4},
            {"stock": "Coal India", "sector": "Energy", "weight": 3.6},
            {"stock": "ICICI Bank", "sector": "Financial Services", "weight": 3.9},
            {"stock": "Amazon", "sector": "Consumer", "weight": 4.1},
            {"stock": "HCL Technologies", "sector": "IT", "weight": 2.8},
        ],
    },
    "mirae-largemid": {
        "current": [
            {"stock": "HDFC Bank", "sector": "Financial Services", "weight": 6.8},
            {"stock": "ICICI Bank", "sector": "Financial Services", "weight": 5.9},
            {"stock": "Axis Bank", "sector": "Financial Services", "weight": 4.7},
            {"stock": "Trent", "sector": "Consumer", "weight": 4.2},
            {"stock": "Bharat Electronics", "sector": "Capital Goods", "weight": 3.6},
            {"stock": "Polycab India", "sector": "Capital Goods", "weight": 3.3},
            {"stock": "Persistent Systems", "sector": "IT", "weight": 3.1},
            {"stock": "Cummins India", "sector": "Capital Goods", "weight": 2.8},
            {"stock": "PI Industries", "sector": "Materials", "weight": 2.4},
            {"stock": "Apollo Hospitals", "sector": "Healthcare", "weight": 2.2},
        ],
        "previous": [
            {"stock": "HDFC Bank", "sector": "Financial Services", "weight": 7.2},
            {"stock": "ICICI Bank", "sector": "Financial Services", "weight": 5.5},
            {"stock": "Axis Bank", "sector": "Financial Services", "weight": 4.9},
            {"stock": "Trent", "sector": "Consumer", "weight": 3.4},
            {"stock": "Bharat Electronics", "sector": "Capital Goods", "weight": 3.0},
            {"stock": "Polycab India", "sector": "Capital Goods", "weight": 2.8},
            {"stock": "Infosys", "sector": "IT", "weight": 3.6},
            {"stock": "Cummins India", "sector": "Capital Goods", "weight": 2.6},
            {"stock": "Sun Pharma", "sector": "Healthcare", "weight": 2.9},
            {"stock": "Apollo Hospitals", "sector": "Healthcare", "weight": 2.0},
        ],
    },
    "kotak-emerg": {
        "current": [
            {"stock": "Persistent Systems", "sector": "IT", "weight": 4.1},
            {"stock": "Cummins India", "sector": "Capital Goods", "weight": 3.8},
            {"stock": "Solar Industries", "sector": "Materials", "weight": 3.5},
            {"stock": "Supreme Industries", "sector": "Materials", "weight": 3.2},
            {"stock": "Polycab India", "sector": "Capital Goods", "weight": 2.9},
            {"stock": "Coromandel International", "sector": "Materials", "weight": 2.7},
            {"stock": "Tube Investments", "sector": "Auto", "weight": 2.5},
            {"stock": "Schaeffler India", "sector": "Auto", "weight": 2.3},
            {"stock": "Voltas", "sector": "Consumer", "weight": 2.1},
            {"stock": "Astral", "sector": "Materials", "weight": 1.9},
        ],
        "previous": [
            {"stock": "Persistent Systems", "sector": "IT", "weight": 3.6},
            {"stock": "Cummins India", "sector": "Capital Goods", "weight": 3.3},
            {"stock": "Solar Industries", "sector": "Materials", "weight": 3.7},
            {"stock": "Supreme Industries", "sector": "Materials", "weight": 3.0},
            {"stock": "Polycab India", "sector": "Capital Goods", "weight": 2.5},
            {"stock": "Coromandel International", "sector": "Materials", "weight": 2.9},
            {"stock": "Page Industries", "sector": "Consumer", "weight": 2.6},
            {"stock": "Schaeffler India", "sector": "Auto", "weight": 2.4},
            {"stock": "Voltas", "sector": "Consumer", "weight": 2.0},
            {"stock": "Coforge", "sector": "IT", "weight": 1.7},
        ],
    },
    "sbi-smallcap": {
        "current": [
            {"stock": "Kalpataru Projects", "sector": "Capital Goods", "weight": 3.8},
            {"stock": "Blue Star", "sector": "Consumer", "weight": 3.4},
            {"stock": "DOMS Industries", "sector": "Consumer", "weight": 3.1},
            {"stock": "Finolex Industries", "sector": "Materials", "weight": 2.8},
            {"stock": "Triveni Turbine", "sector": "Capital Goods", "weight": 2.6},
            {"stock": "Cholamandalam Financial", "sector": "Financial Services", "weight": 2.3},
            {"stock": "Carborundum Universal", "sector": "Materials", "weight": 2.0},
            {"stock": "City Union Bank", "sector": "Financial Services", "weight": 1.8},
            {"stock": "Whirlpool India", "sector": "Consumer", "weight": 1.6},
            {"stock": "Vesuvius India", "sector": "Materials", "weight": 1.4},
        ],
        "previous": [
            {"stock": "Kalpataru Projects", "sector": "Capital Goods", "weight": 3.2},
            {"stock": "Blue Star", "sector": "Consumer", "weight": 3.6},
            {"stock": "DOMS Industries", "sector": "Consumer", "weight": 2.4},
            {"stock": "Finolex Industries", "sector": "Materials", "weight": 2.9},
            {"stock": "Triveni Turbine", "sector": "Capital Goods", "weight": 2.1},
            {"stock": "Cholamandalam Financial", "sector": "Financial Services", "weight": 2.6},
            {"stock": "Relaxo Footwears", "sector": "Consumer", "weight": 2.3},
            {"stock": "City Union Bank", "sector": "Financial Services", "weight": 1.9},
            {"stock": "Whirlpool India", "sector": "Consumer", "weight": 1.7},
            {"stock": "Galaxy Surfactants", "sector": "Materials", "weight": 1.5},
        ],
    },
    "hdfc-balanced": {
        "current": [
            {"stock": "ICICI Bank", "sector": "Financial Services", "weight": 5.8},
            {"stock": "HDFC Bank", "sector": "Financial Services", "weight": 5.3},
            {"stock": "Reliance Industries", "sector": "Energy", "weight": 4.6},
            {"stock": "Larsen & Toubro", "sector": "Capital Goods", "weight": 3.4},
            {"stock": "Infosys", "sector": "IT", "weight": 2.9},
            {"stock": "ITC", "sector": "Consumer", "weight": 2.6},
            {"stock": "NTPC", "sector": "Utilities", "weight": 2.4},
            {"stock": "State Bank of India", "sector": "Financial Services", "weight": 2.1},
            {"stock": "Maruti Suzuki", "sector": "Auto", "weight": 1.8},
            {"stock": "Coal India", "sector": "Energy", "weight": 1.5},
        ],
        "previous": [
            {"stock": "ICICI Bank", "sector": "Financial Services", "weight": 5.4},
            {"stock": "HDFC Bank", "sector": "Financial Services", "weight": 5.6},
            {"stock": "Reliance Industries", "sector": "Energy", "weight": 4.3},
            {"stock": "Larsen & Toubro", "sector": "Capital Goods", "weight": 3.0},
            {"stock": "Infosys", "sector": "IT", "weight": 3.2},
            {"stock": "ITC", "sector": "Consumer", "weight": 2.9},
            {"stock": "NTPC", "sector": "Utilities", "weight": 2.0},
            {"stock": "State Bank of India", "sector": "Financial Services", "weight": 2.3},
            {"stock": "Tata Motors", "sector": "Auto", "weight": 2.0},
            {"stock": "Coal India", "sector": "Energy", "weight": 1.3},
        ],
    },
}

# Performance: scheme vs category vs benchmark across timeframes (returns in %)
PERFORMANCE = {
    "axis-bluechip": {
        "1Y": {"scheme": 18.4, "category": 21.2, "benchmark": 22.1},
        "3Y": {"scheme": 14.6, "category": 16.8, "benchmark": 17.4},
        "5Y": {"scheme": 16.2, "category": 17.1, "benchmark": 17.8},
        "inception": {"scheme": 13.1, "category": 12.4, "benchmark": 11.9},
        "rolling_3Y": [
            {"period": "2019", "scheme": 11.2, "benchmark": 9.8},
            {"period": "2020", "scheme": 14.7, "benchmark": 13.1},
            {"period": "2021", "scheme": 17.9, "benchmark": 18.4},
            {"period": "2022", "scheme": 12.4, "benchmark": 14.0},
            {"period": "2023", "scheme": 16.1, "benchmark": 17.2},
            {"period": "2024", "scheme": 14.6, "benchmark": 17.4},
        ],
        "benchmark_history": {"5Y": True, "10Y": True, "15Y": True},
        "differentials": {"5Y": -1.6, "10Y": 0.8, "15Y": 1.2},
    },
    "parag-flexi": {
        "1Y": {"scheme": 32.1, "category": 26.4, "benchmark": 24.8},
        "3Y": {"scheme": 21.8, "category": 18.2, "benchmark": 17.1},
        "5Y": {"scheme": 24.2, "category": 19.4, "benchmark": 18.6},
        "inception": {"scheme": 20.4, "category": 14.8, "benchmark": 13.7},
        "rolling_3Y": [
            {"period": "2019", "scheme": 14.6, "benchmark": 9.4},
            {"period": "2020", "scheme": 19.2, "benchmark": 14.8},
            {"period": "2021", "scheme": 27.4, "benchmark": 19.6},
            {"period": "2022", "scheme": 18.7, "benchmark": 14.2},
            {"period": "2023", "scheme": 24.8, "benchmark": 18.4},
            {"period": "2024", "scheme": 21.8, "benchmark": 17.1},
        ],
        "benchmark_history": {"5Y": True, "10Y": True, "15Y": True},
        "differentials": {"5Y": 5.6, "10Y": 6.2, "15Y": 6.7},
    },
    "mirae-largemid": {
        "1Y": {"scheme": 28.6, "category": 25.4, "benchmark": 24.7},
        "3Y": {"scheme": 19.4, "category": 18.1, "benchmark": 18.6},
        "5Y": {"scheme": 22.1, "category": 19.8, "benchmark": 20.2},
        "inception": {"scheme": 18.7, "category": 15.4, "benchmark": 14.8},
        "rolling_3Y": [
            {"period": "2019", "scheme": 13.4, "benchmark": 11.2},
            {"period": "2020", "scheme": 18.7, "benchmark": 16.4},
            {"period": "2021", "scheme": 23.1, "benchmark": 21.8},
            {"period": "2022", "scheme": 16.2, "benchmark": 17.1},
            {"period": "2023", "scheme": 21.4, "benchmark": 19.8},
            {"period": "2024", "scheme": 19.4, "benchmark": 18.6},
        ],
        "benchmark_history": {"5Y": True, "10Y": True, "15Y": False},
        "differentials": {"5Y": 1.9, "10Y": 2.4, "15Y": -0.6},
    },
    "kotak-emerg": {
        "1Y": {"scheme": 31.4, "category": 29.8, "benchmark": 30.2},
        "3Y": {"scheme": 21.6, "category": 22.1, "benchmark": 22.7},
        "5Y": {"scheme": 24.8, "category": 23.4, "benchmark": 24.1},
        "inception": {"scheme": 17.9, "category": 16.2, "benchmark": 15.4},
        "rolling_3Y": [
            {"period": "2019", "scheme": 12.6, "benchmark": 10.8},
            {"period": "2020", "scheme": 19.4, "benchmark": 18.7},
            {"period": "2021", "scheme": 28.1, "benchmark": 27.4},
            {"period": "2022", "scheme": 17.6, "benchmark": 19.2},
            {"period": "2023", "scheme": 23.4, "benchmark": 24.1},
            {"period": "2024", "scheme": 21.6, "benchmark": 22.7},
        ],
        "benchmark_history": {"5Y": True, "10Y": True, "15Y": True},
        "differentials": {"5Y": 0.7, "10Y": 1.4, "15Y": 2.5},
    },
    "sbi-smallcap": {
        "1Y": {"scheme": 27.8, "category": 31.2, "benchmark": 32.4},
        "3Y": {"scheme": 24.6, "category": 25.4, "benchmark": 26.1},
        "5Y": {"scheme": 28.4, "category": 26.8, "benchmark": 25.9},
        "inception": {"scheme": 22.1, "category": 18.4, "benchmark": 17.8},
        "rolling_3Y": [
            {"period": "2019", "scheme": 16.4, "benchmark": 12.4},
            {"period": "2020", "scheme": 21.8, "benchmark": 19.6},
            {"period": "2021", "scheme": 32.4, "benchmark": 30.8},
            {"period": "2022", "scheme": 19.6, "benchmark": 22.4},
            {"period": "2023", "scheme": 26.8, "benchmark": 28.1},
            {"period": "2024", "scheme": 24.6, "benchmark": 26.1},
        ],
        "benchmark_history": {"5Y": True, "10Y": True, "15Y": True},
        "differentials": {"5Y": 2.5, "10Y": 4.2, "15Y": 4.3},
    },
    "hdfc-balanced": {
        "1Y": {"scheme": 19.4, "category": 17.6, "benchmark": 14.8},
        "3Y": {"scheme": 14.8, "category": 13.2, "benchmark": 11.4},
        "5Y": {"scheme": 16.7, "category": 14.4, "benchmark": 12.6},
        "inception": {"scheme": 12.8, "category": 10.4, "benchmark": 9.6},
        "rolling_3Y": [
            {"period": "2019", "scheme": 8.4, "benchmark": 7.2},
            {"period": "2020", "scheme": 11.6, "benchmark": 9.8},
            {"period": "2021", "scheme": 16.4, "benchmark": 13.4},
            {"period": "2022", "scheme": 13.8, "benchmark": 11.2},
            {"period": "2023", "scheme": 17.2, "benchmark": 13.6},
            {"period": "2024", "scheme": 14.8, "benchmark": 11.4},
        ],
        "benchmark_history": {"5Y": True, "10Y": True, "15Y": True},
        "differentials": {"5Y": 4.1, "10Y": 3.6, "15Y": 3.2},
    },
}

# Asset allocation: equity / debt / cash (current vs previous)
ASSET_ALLOCATION = {
    "axis-bluechip": {"current": {"equity": 96.4, "debt": 0.0, "cash": 3.6},
                      "previous": {"equity": 97.8, "debt": 0.0, "cash": 2.2}},
    "parag-flexi": {"current": {"equity": 80.4, "debt": 5.2, "cash": 14.4},
                    "previous": {"equity": 78.1, "debt": 4.9, "cash": 17.0}},
    "mirae-largemid": {"current": {"equity": 98.2, "debt": 0.0, "cash": 1.8},
                       "previous": {"equity": 98.6, "debt": 0.0, "cash": 1.4}},
    "kotak-emerg": {"current": {"equity": 95.8, "debt": 0.0, "cash": 4.2},
                    "previous": {"equity": 96.7, "debt": 0.0, "cash": 3.3}},
    "sbi-smallcap": {"current": {"equity": 88.4, "debt": 0.0, "cash": 11.6},
                     "previous": {"equity": 92.1, "debt": 0.0, "cash": 7.9}},
    "hdfc-balanced": {"current": {"equity": 64.8, "debt": 28.4, "cash": 6.8},
                      "previous": {"equity": 71.2, "debt": 24.1, "cash": 4.7}},
}


def build_alerts():
    """Generate alerts based on diffs in mock data."""
    now = datetime.now(timezone.utc)
    alerts = []

    # Manager change: Parag Parikh added co-manager, HDFC added a manager
    alerts.append({
        "id": "alrt-001", "fund_id": "parag-flexi", "type": "manager_change",
        "severity": "high",
        "title": "Fund Manager Change",
        "message": "Raunak Onkar added as co-manager alongside Rajeev Thakkar.",
        "created_at": (now - timedelta(days=2)).isoformat(),
    })
    alerts.append({
        "id": "alrt-002", "fund_id": "hdfc-balanced", "type": "manager_change",
        "severity": "high",
        "title": "Fund Manager Change",
        "message": "Srinivasan Ramamurthy added as additional fund manager.",
        "created_at": (now - timedelta(days=5)).isoformat(),
    })
    # Category reclassification
    alerts.append({
        "id": "alrt-003", "fund_id": "parag-flexi", "type": "category_reclassification",
        "severity": "medium",
        "title": "SEBI Category Reclassified",
        "message": "Re-categorised from 'Multi Cap' to 'Flexi Cap'.",
        "created_at": (now - timedelta(days=14)).isoformat(),
    })
    # Objective change
    alerts.append({
        "id": "alrt-004", "fund_id": "sbi-smallcap", "type": "objective_change",
        "severity": "medium",
        "title": "Investment Objective Amended",
        "message": "Scheme objective updated to focus predominantly on small cap equities.",
        "created_at": (now - timedelta(days=9)).isoformat(),
    })
    # Name change
    alerts.append({
        "id": "alrt-005", "fund_id": "mirae-largemid", "type": "name_change",
        "severity": "low",
        "title": "Fund Name Changed",
        "message": "Renamed from 'Mirae Asset Emerging Bluechip Fund' to 'Mirae Asset Large & Midcap Fund'.",
        "created_at": (now - timedelta(days=20)).isoformat(),
    })
    # Asset allocation shift
    alerts.append({
        "id": "alrt-006", "fund_id": "hdfc-balanced", "type": "asset_allocation",
        "severity": "high",
        "title": "Asset Allocation Shift",
        "message": "Equity allocation reduced from 71.2% to 64.8% (-6.4%). Debt up by +4.3%.",
        "created_at": (now - timedelta(days=1)).isoformat(),
    })
    alerts.append({
        "id": "alrt-007", "fund_id": "sbi-smallcap", "type": "asset_allocation",
        "severity": "medium",
        "title": "Cash Position Increased",
        "message": "Cash position rose from 7.9% to 11.6% (+3.7%) — defensive positioning.",
        "created_at": (now - timedelta(days=3)).isoformat(),
    })
    return alerts


ALERTS = build_alerts()


def fund_by_id(fund_id):
    return next((f for f in FUNDS if f["id"] == fund_id), None)
